from __future__ import annotations

# Import all exported variables and functions from individual modules

# Common utility functions
from studyfrog.utils.common import (
    create_rgb_bg_color,
    create_rgb_fg_color,
    date_from_string,
    datetime_from_string,
    exists,
    filter_and_call,
    find_string,
    flatten_dictionary,
    generate_model_key,
    generate_uuid4,
    generate_uuid4_str,
    get_date_from_string,
    get_datetime_from_string,
    get_time_from_string,
    get_now,
    get_now_iso_str,
    get_today,
    get_today_iso_str,
    is_empty,
    is_none,
    is_none_or_empty,
    is_not_none,
    is_not_none_or_empty,
    match_string,
    model_key_to_model_type,
    path_from_string,
    pluralize_word,
    search_string,
    shuffle_list,
    simple_dict_to_string,
    simple_string_to_dict,
    singularize_word,
    string_to_snake_case,
    uuid_from_string,
)

# Directory utilities
from studyfrog.utils.directories import (
    create_directory,
    does_directory_exist,
    ensure_directory,
    is_directory_empty,
    remove_directory,
)

# Dispatcher utilities
from studyfrog.utils.dispatcher import (
    bulk_dispatch,
    bulk_subscribe,
    bulk_unsubscribe,
    dispatch,
    subscribe,
    unsubscribe,
)

# File utilities
from studyfrog.utils.files import (
    create_file,
    does_file_exist,
    does_file_have_content,
    ensure_file,
    read_file_json,
    read_file_text,
    remove_file,
    write_file_json,
    write_file_text,
)

# GUI utilities
from studyfrog.utils.gui import (
    clear_center_frame,
    clear_bottom_frame,
    clear_frames,
    clear_top_frame,
    count_widget_children,
    destroy_widget_children,
    get_widget_children,
    reset_bottom_frame_grid,
    reset_center_frame_grid,
    reset_frame_grids,
    reset_top_frame_grid,
    reset_widget_grid,
)

# Logging utilities
from studyfrog.utils.logging import (
    log,
    log_critical,
    log_debug,
    log_error,
    log_info,
    log_success,
    log_trace,
    log_warning,
    LogLevel,  # TypeAlias
)

# Model utilities
from studyfrog.utils.models import (
    count_models,
    create_model,
    create_models,
    delete_model,
    delete_models,
    filter_models,
    read_all_models,
    read_model,
    read_model_by_key,
    read_models,
    read_models_by_keys,
    update_model,
    update_models,
)

# Storage utilities
from studyfrog.utils.storage import (
    add_entry,
    add_entry_if_not_exist,
    add_entries,
    add_entries_if_not_exist,
    count_entries,
    delete_entry,
    delete_entries,
    filter_entries,
    get_all_entries,
    get_entries,
    get_entries_by_keys,
    get_entry,
    get_entry_by_key,
    update_entry,
    update_entries,
)

# Export all utilities
__all__: list[str] = [
    # Common utility functions
    "create_rgb_bg_color",
    "create_rgb_fg_color",
    "date_from_string",
    "datetime_from_string",
    "exists",
    "filter_and_call",
    "find_string",
    "flatten_dictionary",
    "generate_model_key",
    "generate_uuid4",
    "generate_uuid4_str",
    "get_date_from_string",
    "get_datetime_from_string",
    "get_time_from_string",
    "get_now",
    "get_now_iso_str",
    "get_today",
    "get_today_iso_str",
    "is_empty",
    "is_none",
    "is_none_or_empty",
    "is_not_none",
    "is_not_none_or_empty",
    "match_string",
    "model_key_to_model_type",
    "path_from_string",
    "pluralize_word",
    "search_string",
    "shuffle_list",
    "simple_dict_to_string",
    "simple_string_to_dict",
    "singularize_word",
    "string_to_snake_case",
    "uuid_from_string",
    # Directory utilities
    "create_directory",
    "does_directory_exist",
    "ensure_directory",
    "is_directory_empty",
    "remove_directory",
    # Dispatcher utilities
    "bulk_dispatch",
    "bulk_subscribe",
    "bulk_unsubscribe",
    "dispatch",
    "subscribe",
    "unsubscribe",
    # File utilities
    "create_file",
    "does_file_exist",
    "does_file_have_content",
    "ensure_file",
    "read_file_json",
    "read_file_text",
    "remove_file",
    "write_file_json",
    "write_file_text",
    # GUI utilities
    "clear_center_frame",
    "clear_bottom_frame",
    "clear_frames",
    "clear_top_frame",
    "count_widget_children",
    "destroy_widget_children",
    "get_widget_children",
    "reset_bottom_frame_grid",
    "reset_center_frame_grid",
    "reset_frame_grids",
    "reset_top_frame_grid",
    "reset_widget_grid",
    # Logging utilities
    "log",
    "log_critical",
    "log_debug",
    "log_error",
    "log_info",
    "log_success",
    "log_trace",
    "log_warning",
    "LogLevel",  # TypeAlias
    # Model utilities
    "count_models",
    "create_model",
    "create_models",
    "delete_model",
    "delete_models",
    "filter_models",
    "read_all_models",
    "read_model",
    "read_model_by_key",
    "read_models",
    "read_models_by_keys",
    "update_model",
    "update_models",
    # Storage utilities
    "add_entry",
    "add_entry_if_not_exist",
    "add_entries",
    "add_entries_if_not_exist",
    "count_entries",
    "delete_entry",
    "delete_entries",
    "filter_entries",
    "get_all_entries",
    "get_entries",
    "get_entries_by_keys",
    "get_entry",
    "get_entry_by_key",
    "update_entry",
    "update_entries",
]
